name: 部署项目到github pages
on: push
jobs: 
  task1:
    name: 检出main分支代码并构建
    runs-on: unbuntu-lastest
    
    steps:
    - name: 检出main分支代码
      uses: actions/checkout@lastest
      
    - name: 安装项目依赖  
      run: pnpm install
      
    - name: 构建代码  
      run: pnpm build
    
    
